### ISSUE TITLE
Scrollable view changes state on device rotation

### ISSUE THREAD

**Issue by reverse-unina** [grmpl/StepandHeightcounter#10]
When I perform this sequence of events, the scrollable view on screen goes back to the top:
1. Click on Settings icon
2. Scroll Down
3. Orientation Change

**Comment by grmpl** [comment]
Thank you for taking interest in my application. But sorry: I don't think I will fix this.

That's out of the box with preferences.xml and standard code. A nuisance but nothing dramatic, as nobody will be using settings all the time with screen orientation changing. One can simply scroll down again if it happens and it's not easy for me to find a solution.

As it's open source feel free to change it. I'm looking forward to a pull request. :-)

**Comment by grmpl** [comment]
As already written, I won't fix this issue.
