### ISSUE TITLE
Update app

### ISSUE THREAD

**Issue by rorybee** [grmpl/StepandHeightcounter#11]
I would like to update this app to API 30. Are you accepting PRs?

**Comment by grmpl** [comment]
Yes, feel free. I didn't do any maintenance on this project for a long time, so I would appreciate any contribution.

**Comment by rorybee** [comment]
Thanks! Will this auto update on fdroid?

**Comment by grmpl** [comment]
When I generate a release and the release builds correctly for F-Droid, it should be automatically updated after a few days on F-droid. Send me your pull request and I will take care.

**Comment by grmpl** [comment]
New release generated, waiting to be published in F-Droid.

**Comment by grmpl** [comment]
New version found by updater from F-droid. I run a build check and corrected the release tag. I forgot: It must be identical to the one in build.gradle. Waiting for f-droid build.
The description in F-Droid must be updated. But this can only be done by merge request. I will wait for build to finish first.

**Comment by grmpl** [comment]
Still waiting for F-Droid to publish. Build has finished successful 2 days ago:
**[https://f-droid.org/wiki/page/grmpl.mk.stepandheightcounter/lastbuild_6](https://f-droid.org/wiki/page/grmpl.mk.stepandheightcounter/lastbuild_6)**

**Comment by rorybee** [comment]
It has been updated.
