### ISSUE TITLE
[FEATURE] Log climbing down

### ISSUE THREAD

**Issue by rorybee** [grmpl/StepandHeightcounter#12]
Add logging of climbing down stairs ( elevation decrease)

**Comment by grmpl** [comment]
@duggalsu: As I'm now familiar again with the process of building a new app release, I think I could do this. Can you tell me, what you mean by "logging"? Is it just a logging in the statistics files or do you want it displayed on the main screen, too?

**Comment by rorybee** [comment]
It would be nice to have a display on the main screen too!

**Comment by grmpl** [comment]
Added in Branch v13, ready for testing.

**Comment by grmpl** [comment]
Version 1.5 is available on F-Droid. Can I close the issue?
