### ISSUE TITLE
[FEATURE] Add stopwatch

### ISSUE THREAD

**Issue by rorybee** [grmpl/StepandHeightcounter#15]
It would be great to have this feature for challenges. The stopwatch should start on recording. 

It would be nice to have a button to reset the stopwatch instead of the time clearing on stopping recording. This would help share challenge completion details.

**Comment by rorybee** [comment]
On second thought,  it would be better for the clock to start from zero on the start of recording. It would be cleaner and a simpler implementation, while also preventing resetting the clock randomly during a challenge

**Comment by grmpl** [comment]
It's not necessary: You can enable Start- and Stop-Markers in the detailed statistics and calculate the time by yourself. ;-)

But a display of recording time would be nice, you're right. I would handle it like steps and height: Cumulate over multiple recordings, pausing in between and setting to 0 when Reset-button is pressed. I will have a look with the descending elevation issue.

**Comment by grmpl** [comment]
Added in Branch v13, ready for testing.
It's a quick&dirty implementation: Time is counted along with steps and height. So it is only updated on step sensor events received.
If you are standing still and then after some time stop measurement, the time from last step until stopping of measurement is not counted. I think, this should be sufficient at first, as one is mainly interested in activity, not in pausing.

**Comment by rorybee** [comment]
Sounds good! Will wait for the release to test.

**Comment by grmpl** [comment]
Just to make clear: Today Version 1.30 was released by F-Droid. This is just an intermediate version where I only changed metadata for F-droid. I waited for it to finish before releasing new features.
Next release with new features will be 1.50.

**Comment by grmpl** [comment]
Version 1.5 with stopwatch is available on F-Droid. Can I close the issue?
