### ISSUE TITLE
Log file creation

### ISSUE THREAD

**Issue by rorybee** [grmpl/StepandHeightcounter#19]
Log files are not being created on Android 11 in v.1.22. I believe this needs to be investigated further with the update to SDK 11.

**Comment by grmpl** [comment]
Are you sure? I have only an Android 10 smartphone and it's working fine there.
I'm not sure if you know: Due to scoped storage logfiles cannot be saved in root directory of SD-card anymore. They will always be saved in Android/data/grmpl.mk.stepandheightcounter/files/StepandHeightCounter/ . And they will always be deleted when deinstalling the app.

**Comment by rorybee** [comment]
Yes, I checked at that location. I will test again and let you know.

**Comment by rorybee** [comment]
Good to know its working on Android 10 on your end.

**Comment by grmpl** [comment]
When measurement is active and you save a marker (orange button), there should a file be created.

**Comment by rorybee** [comment]
Is it only created if you press the marker?

**Comment by rorybee** [comment]
Yes, it's created if I press the marker :)

**Comment by rorybee** [comment]
If we save the file on every run automatically, it might be helpful for features eg for plotting graphs.

**Comment by grmpl** [comment]
You can, you just have to adapt the settings:

- There are regular statistics, daily  statistics and detailed statistics
- Regular statistics are written in a fixed interval (1/4, 1/2, 1 hour). They are not activated by default. You have to activate them in the settings.
- Daily statistics are written by default. But they are written only at the end of a day and only when measurement is active. So you have to wait for one day for the file to be created.
- Detailed statistics are saving various events. Marker is a part of detailed statistics and is the only event activated by default. So if you save a marker, it will be saved in file for detailed statistics.
- Additional events like Start/Stop of measurement can be activated in the settings. If such an event is happening, and it is activated in the setting, it will be saved in the file for detailed statistics.

So if you want to plot graphs, you can either activate regular statistics or for a very detailed analysis all the events in the detailed statistics.

**Comment by rorybee** [comment]
My mistake. I thought I had all statistics enabled after re-install. Thanks for the detailed logging description!
