### ISSUE TITLE
Content does not fit on a phone screen and gets cut off

### ISSUE THREAD

**Issue by whitequark** [grmpl/StepandHeightcounter#5]
I'm using the 1.1 version from F-Droid on Xperia Z2. Here's a screenshot:
![screenshot_2017-01-03-03-23-22](https://cloud.githubusercontent.com/assets/54771/21597950/f996b79a-d14a-11e6-8a0c-e15ad5d51e1b.png)

I think you could add a scroll box and/or remove that huge space under the "start/stop measurement" button.

**Comment by grmpl** [comment]
Thanks for your feedback. So there is another device, where it is working.

Although I have checked the layout for some devices in Android Studio, it is optimized for my device. Some spaces could be removed, but then it looks ugly on my device. ;-) 

Could you tell me, what screensize, resolution and textsize you are using?
Because:
* Xperia Z2 should have exact the same screen size as Nexus 5X (5,2", 1080x1920)
* in Android Studio I can reproduce your problem only with very small screen sizes (4", 480x800)
* even with the small screen sizes your screenshot looks different. It seems to me, your text size is enlarged. With 130% font scaling, my layout looks similar, but nevertheless I don't get your height problem.

**Comment by whitequark** [comment]
> even with the small screen sizes your screenshot looks different. It seems to me, your text size is enlarged.

Yes, my font size is enlarged, to 115%. Isn't the point of the Android layout engine to make this irrelevant to apps?

**Comment by grmpl** [comment]
Maybe it should, but I'm new to Android programming and don't know, how this can be irrelevant: If text is scaled it will use more/less space and layout will change. So one have to take this into account in some way.

I've tried to insert some scrollviews. It's not very elegant but it seems to be working. Can you try out my latest commit? Do you need an apk, or can you compile it by yourself? 
Please do try out the landscape mode, too.

**Comment by whitequark** [comment]
Could you upload an apk? I did some Android development but it would take me quite a while to set up the environment from scratch right now, and you probably already have an apk built anyway.

**Comment by grmpl** [comment]
I've attached the debug-apk. 
But I have just found an error: The app will crash when rotating to landscape mode and back again. Nevertheless, you should be able just to check if the layout is working.
[app-debug.apk.zip](https://github.com/grmpl/StepandHeightcounter/files/683177/app-debug.apk.zip)

**Comment by whitequark** [comment]
This fixes portrait mode, but not landscape mode, unfortunately, which still cuts off even with scrolling:
![screenshot_2017-01-04-00-20-02](https://cloud.githubusercontent.com/assets/54771/21623483/78d95a08-d1fa-11e6-8e9d-01ea79f6a438.png)

**Comment by grmpl** [comment]
Hi,
sorry, the Java exception needed some time to get rid off.
I have two workarounds for the exceptions: One with a layout change (landscape is scrolling the complete screen) and one with just a code change (which is not very elegant ;-) ).
Could you please test these two versions and say which you like better?
[stepandheight_variant1_debug.apk.zip](https://github.com/grmpl/StepandHeightcounter/files/685566/stepandheight_variant1_debug.apk.zip)
[stepandheight_variant2_debug.apk.zip](https://github.com/grmpl/StepandHeightcounter/files/685565/stepandheight_variant2_debug.apk.zip)
Your last problem should be solved in both versions.

**Comment by grmpl** [comment]
As I didn't get an answer yet, I've released Version 1.2 with the first variant. 
It should be available on FDroid in a few days.

**Comment by whitequark** [comment]
@grmpl Sorry for the delay--my phone has been stolen yesterday (I think?) and I do not have a replacement yet.

**Comment by grmpl** [comment]
@whitequark That's really bad. :-(
The delay is no problem. I just wanted to have it fixed, so I had to decide myself. ;-)
Thank you for the input.
