### ISSUE TITLE
Dialog disappears on device rotation 

### ISSUE THREAD

**Issue by reverse-unina** [grmpl/StepandHeightcounter#9]
When i perform these sequences of events, the dialog on screen disappears:

1. Click on Settings icon
2. Click on:
a. Steps
b. Height
c. Detailed Statistics
d. Maximum files
e. Autoclean of detailed statistics data
f. Interval
g. Autoclean of regular statistics
h. Maximum files
3. Orientation Change

**Comment by grmpl** [comment]
Same as in other issue #10 : I don't think I will fix this.

You don't have to take all these steps. Just open the dialog in Settings first and rotate device.
Again: Just a nuisance. One small additional touch for the user and a giant effort for me to fix it. ;-)

**Comment by grmpl** [comment]
same here: won't fix
